#!/bin/sh

# Get the current version number
version=$(git describe --tags $(git rev-list --tags --max-count=1) --long)

# Replace first dash with plus
version=$(echo $version | sed "s/-/+/")

# Save the version number to a file
echo $version > .version

# Find all Python files in the repository
files=$(git diff --name-only --staged | grep ".py")

# Replace the __version__ variable in each file
for file in $files; do
    sed -i "s/__version__ = .*/__version__ = '$version'/" $file
done

# Build the documentation
if [ -d doc/fire2a-lib ]; then
    rm -r doc/fire2a-lib
fi
pdoc --html --force --output-dir doc --filter=src,tests --config latex_math=True .

# Add the modified files to the commit
git add .version $files doc/fire2a-lib/*
