#!/bin/sh

# Get the current version from git
# version=$(git describe --dirty)
version=$(git describe --always --dirty --long)

# Find all Python files in the repository
files=$(find . -type f -name "*.py")

# Replace the __version__ variable in each file
for file in $files; do
    sed -i "s/__version__ = .*/__version__ = '$version'/" $file
done

# Add the modified files to the commit
git add $files

sed -i "5 s/__version__ = .*/__version__ = '$version'/" README.md
git add README.md
