#!/bin/sh

# Build the documentation
if [ -d doc/fire2a-lib ]; then
    rm -fr doc/fire2a-lib
fi
pdoc --html --force --output-dir doc --filter=src,tests --config latex_math=True .

# Add the modified files to the commit
git add doc/fire2a-lib/*
git commit --amend --no-edit
