name: Test Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [
          'qgis/qgis:release-3_28',
          'qgis/qgis:release-3_30',
          'qgis/qgis:3.40-noble',
          'qgis/qgis:3.40-jammy'
        ]

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Inspect
      run: |
        qgis --version
        python3 -V

        # - name: Install system dependencies
        #   run: |
        #     apt-get update
        #     apt-get install -y python3-pip python3-venv

    - name: Install dependencies
      run: |
        python3 -m venv .venv --system-site-packages
        . .venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir pytest

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -V
        pytest
