name: Test Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [
          'qgis/qgis:release-3_28',
          'qgis/qgis:release-3_30',
          'qgis/qgis:3.40-noble',
          'qgis/qgis:3.40-jammy'
        ]

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Inspect
      run: |
        qgis --version
        python3 -V
        echo $SHELL

    - name: do it
      run: |
        apt-get install -y python3-numpy python3-matplotlib python3-venv python3-pip
        apt-get remove -y python3-pytest
        python3 -m venv .venv --system-site-packages
        . .venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir pytest
        python -m pytest
      shell: bash
