name: Test Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [
          'qgis/qgis:ltr-disco',
          'qgis/qgis:ltr-lunar',
          'qgis/qgis:ltr-focal',
          'qgis/qgis:ltr-noble',
          'qgis/qgis:ltr-jammy'
        ]

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Inspect
      run: |
        qgis --version
        python3 -V
        echo $SHELL

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-venv
        apt-get remove -y python3-pytest
        python3 -m venv .venv --system-site-packages
        . .venv/bin/activate
        python3 -m pip install --upgrade pip setuptools wheel pytest
        pip install --no-cache-dir -r requirements.txt
      shell: bash

    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest
      shell: bash
